#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>
#define SOCKET_PATH "/run/nuubos/usersd.sock"
static int write_all(int fd,const char*s){size_t n=strlen(s);while(n){ssize_t w=write(fd,s,n);if(w<0){if(errno==EINTR)continue;return-1;}s+=w;n-=(size_t)w;}return 0;}
int main(int argc,char**argv){int fd;struct sockaddr_un a;char cmd[1024],buf[2048];ssize_t n;if(argc<2)return 2;if(!strcmp(argv[1],"status"))snprintf(cmd,sizeof(cmd),"STATUS\n");else if(!strcmp(argv[1],"activate")&&argc==3)snprintf(cmd,sizeof(cmd),"ACTIVATE\t%s\n",argv[2]);else if(!strcmp(argv[1],"create")&&argc>=3)snprintf(cmd,sizeof(cmd),"CREATE\t%s\n",argv[2]);else if(!strcmp(argv[1],"set-name")&&argc>=4)snprintf(cmd,sizeof(cmd),"SET_NAME\t%s\t%s\n",argv[2],argv[3]);else if(!strcmp(argv[1],"set-avatar")&&argc==4)snprintf(cmd,sizeof(cmd),"SET_AVATAR\t%s\t%s\n",argv[2],argv[3]);else if(!strcmp(argv[1],"delete")&&argc==3)snprintf(cmd,sizeof(cmd),"DELETE\t%s\tCONFIRM\n",argv[2]);else if(!strcmp(argv[1],"set-login-mode")&&argc==3)snprintf(cmd,sizeof(cmd),"SET_LOGIN_MODE\t%s\n",argv[2]);else if(!strcmp(argv[1],"set-default")&&argc==3)snprintf(cmd,sizeof(cmd),"SET_DEFAULT\t%s\n",argv[2]);else if(!strcmp(argv[1],"request-switch"))snprintf(cmd,sizeof(cmd),"REQUEST_SWITCH\n");else if(!strcmp(argv[1],"cancel-switch"))snprintf(cmd,sizeof(cmd),"CANCEL_SWITCH\n");else if(!strcmp(argv[1],"list-avatars")&&argc==3)snprintf(cmd,sizeof(cmd),"LIST_AVATARS\t%s\n",argv[2]);else return 2;fd=socket(AF_UNIX,SOCK_STREAM,0);if(fd<0)return 1;memset(&a,0,sizeof(a));a.sun_family=AF_UNIX;snprintf(a.sun_path,sizeof(a.sun_path),"%s",SOCKET_PATH);if(connect(fd,(struct sockaddr*)&a,sizeof(a))!=0){perror("connect");close(fd);return 1;}if(write_all(fd,cmd)){close(fd);return 1;}shutdown(fd,SHUT_WR);while((n=read(fd,buf,sizeof(buf)))>0)fwrite(buf,1,(size_t)n,stdout);close(fd);return 0;}
