#include <ctype.h>
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <ftw.h>
#include <poll.h>
#include <signal.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/un.h>
#include <unistd.h>
#define SOCKET_PATH "/run/nuubos/usersd.sock"
#define PIDFILE "/run/nuubos/usersd.pid"
#define USERS_DIR "/state/users"
#define ACTIVE_FILE "/run/nuubos/user/active"
#define DEVICE_CONFIG "/state/config/nuubos.conf"
#define AVATAR_DIR "/usr/share/nuubos/avatars"
#define AVATAR_BUILTIN_COUNT 24
#define MAX_CLIENTS 12
#define MAX_USERS 32
struct client{int fd;bool subscribed;char buf[1024];size_t used;};
struct user_info{char id[64];char name[128];char avatar[256];};
static struct client clients[MAX_CLIENTS];static volatile sig_atomic_t stop_requested;static bool switch_requested;
static void on_signal(int s){(void)s;stop_requested=1;}
static int write_all(int fd,const char*s){size_t n=strlen(s);while(n){ssize_t w=write(fd,s,n);if(w<0){if(errno==EINTR)continue;return-1;}s+=w;n-=(size_t)w;}return 0;}
static void trim(char*s){char*p=s;size_t n;while(*p&&isspace((unsigned char)*p))p++;if(p!=s)memmove(s,p,strlen(p)+1);n=strlen(s);while(n&&isspace((unsigned char)s[n-1]))s[--n]='\0';}
static bool valid_id(const char*s){size_t i,n=strlen(s);if(n!=36)return false;for(i=0;i<n;i++){if(i==8||i==13||i==18||i==23){if(s[i]!='-')return false;}else if(!isxdigit((unsigned char)s[i]))return false;}return true;}
static bool valid_name(const char*s){size_t i,n=strlen(s);if(n<1||n>64)return false;for(i=0;i<n;i++){unsigned char c=(unsigned char)s[i];if(c<' '||c==0x7f||c=='\n'||c=='\r'||c=='\t')return false;}return true;}
static bool safe_avatar_spec(const char*s){if(!strncmp(s,"builtin:",8)){const char*p=s+8;return strlen(p)==2&&isdigit((unsigned char)p[0])&&isdigit((unsigned char)p[1]);}if(!strncmp(s,"custom:",7)){const char*p=s+7;size_t i,n=strlen(p);if(!n||n>120||strstr(p,"..")||strchr(p,'/'))return false;for(i=0;i<n;i++){unsigned char c=(unsigned char)p[i];if(!(isalnum(c)||c=='.'||c=='_'||c=='-'||c==' '))return false;}return true;}return false;}
static bool read_line_file(const char*path,char*out,size_t sz){FILE*f=fopen(path,"r");if(!f)return false;if(!fgets(out,(int)sz,f)){fclose(f);return false;}fclose(f);trim(out);return true;}
static bool read_kv(const char*path,const char*key,char*out,size_t sz){FILE*f=fopen(path,"r");char line[512];size_t k=strlen(key);if(!f)return false;while(fgets(line,sizeof(line),f)){trim(line);if(!strncmp(line,key,k)&&line[k]=='='){snprintf(out,sz,"%s",line+k+1);fclose(f);return true;}}fclose(f);return false;}
static int write_atomic_text(const char*path,const char*text,mode_t mode){char tmp[512];FILE*f;snprintf(tmp,sizeof(tmp),"%s.tmp.%ld",path,(long)getpid());f=fopen(tmp,"w");if(!f)return-1;if(fputs(text,f)==EOF||fflush(f)||fsync(fileno(f))){fclose(f);unlink(tmp);return-1;}fclose(f);chmod(tmp,mode);if(rename(tmp,path)){unlink(tmp);return-1;}return 0;}
static int update_config(const char*key,const char*value){FILE*in,*out;char tmp[512],line[512];bool found=false;mkdir("/state/config",0755);snprintf(tmp,sizeof(tmp),"%s.tmp.%ld",DEVICE_CONFIG,(long)getpid());in=fopen(DEVICE_CONFIG,"r");out=fopen(tmp,"w");if(!out){if(in)fclose(in);return-1;}if(in){size_t k=strlen(key);while(fgets(line,sizeof(line),in)){if(!strncmp(line,key,k)&&line[k]=='='){fprintf(out,"%s=%s\n",key,value);found=true;}else fputs(line,out);}fclose(in);}if(!found)fprintf(out,"%s=%s\n",key,value);if(fflush(out)||fsync(fileno(out))){fclose(out);unlink(tmp);return-1;}fclose(out);chmod(tmp,0600);if(rename(tmp,DEVICE_CONFIG)){unlink(tmp);return-1;}return 0;}
static void config_value(const char*k,char*out,size_t sz,const char*def){if(!read_kv(DEVICE_CONFIG,k,out,sz)||!out[0])snprintf(out,sz,"%s",def);}
static int read_profile(const char*id,struct user_info*u){char path[128];if(!valid_id(id))return-1;snprintf(path,sizeof(path),USERS_DIR"/%.36s/profile.conf",id);if(access(path,R_OK))return-1;snprintf(u->id,sizeof(u->id),"%.36s",id);if(!read_kv(path,"USER_NAME",u->name,sizeof(u->name)))snprintf(u->name,sizeof(u->name),"Player");if(!read_kv(path,"USER_AVATAR",u->avatar,sizeof(u->avatar)))snprintf(u->avatar,sizeof(u->avatar),"builtin:01");return 0;}
static int save_profile(const struct user_info*u){char path[128],text[768];snprintf(path,sizeof(path),USERS_DIR"/%.36s/profile.conf",u->id);snprintf(text,sizeof(text),"NUUBOS_USER_PROFILE_VERSION=1\nUSER_ID=%.36s\nUSER_NAME=%.64s\nUSER_AVATAR=%.255s\n",u->id,u->name,u->avatar);return write_atomic_text(path,text,0600);}
static int cmp_users(const void*a,const void*b){return strcasecmp(((const struct user_info*)a)->name,((const struct user_info*)b)->name);}
static int list_users(struct user_info*u,int cap){DIR*d=opendir(USERS_DIR);struct dirent*e;int n=0;if(!d)return 0;while((e=readdir(d))){if(e->d_name[0]=='.'||n>=cap)continue;if(read_profile(e->d_name,&u[n])==0)n++;}closedir(d);qsort(u,(size_t)n,sizeof(u[0]),cmp_users);return n;}
static void active_id(char*out,size_t sz){if(!read_line_file(ACTIVE_FILE,out,sz))out[0]='\0';}
static void avatar_path(const struct user_info*u,char*out,size_t sz){if(!strncmp(u->avatar,"builtin:",8))snprintf(out,sz,AVATAR_DIR"/%.2s.png",u->avatar+8);else if(!strncmp(u->avatar,"custom:",7))snprintf(out,sz,"/userdata/users/%.36s/profile/avatars/%.120s",u->id,u->avatar+7);else snprintf(out,sz,AVATAR_DIR"/01.png");}
static void send_status(int fd){struct user_info users[MAX_USERS];int n=list_users(users,MAX_USERS),i;char active[64],mode[32],def[64],last_user[64],line[1536];active_id(active,sizeof(active));config_value("USER_LOGIN_MODE",mode,sizeof(mode),"AUTO");config_value("DEFAULT_USER",def,sizeof(def),"");config_value("LAST_USER",last_user,sizeof(last_user),"");if(!strcmp(mode,"AUTO"))snprintf(mode,sizeof(mode),"SELECT");snprintf(line,sizeof(line),"active=%s\ncount=%d\nlogin_mode=%s\ndefault_user=%s\nlast_user=%s\nselection_required=%d\nswitch_requested=%d\n",active,n,!strcasecmp(mode,"DEFAULT")?"default":"select",def,last_user,(n>1&&!active[0])?1:0,switch_requested?1:0);write_all(fd,line);for(i=0;i<n;i++){char path[512];avatar_path(&users[i],path,sizeof(path));snprintf(line,sizeof(line),"user=%.36s\t%.64s\t%.255s\t%.511s\t%d\t%d\n",users[i].id,users[i].name,users[i].avatar,path,!strcmp(active,users[i].id),!strcmp(def,users[i].id));write_all(fd,line);}write_all(fd,"end=1\n");}
static void notify_all(void){int i;for(i=0;i<MAX_CLIENTS;i++)if(clients[i].fd>=0&&clients[i].subscribed)send_status(clients[i].fd);}
static void migrate_profiles(void){struct user_info users[MAX_USERS];int i,n=list_users(users,MAX_USERS);for(i=0;i<n;i++)if(!safe_avatar_spec(users[i].avatar)){snprintf(users[i].avatar,sizeof(users[i].avatar),"builtin:01");(void)save_profile(&users[i]);}}
static int make_listener(void){int fd;struct sockaddr_un a;mkdir("/run/nuubos",0755);unlink(SOCKET_PATH);fd=socket(AF_UNIX,SOCK_STREAM|SOCK_NONBLOCK|SOCK_CLOEXEC,0);if(fd<0)return-1;memset(&a,0,sizeof(a));a.sun_family=AF_UNIX;snprintf(a.sun_path,sizeof(a.sun_path),"%s",SOCKET_PATH);if(bind(fd,(struct sockaddr*)&a,sizeof(a))||listen(fd,12)){close(fd);return-1;}chmod(SOCKET_PATH,0660);return fd;}
static void accept_clients(int l){for(;;){int fd=accept4(l,NULL,NULL,SOCK_NONBLOCK|SOCK_CLOEXEC),i;if(fd<0)return;for(i=0;i<MAX_CLIENTS;i++)if(clients[i].fd<0)break;if(i==MAX_CLIENTS){close(fd);continue;}clients[i]=(struct client){.fd=fd};}}
static int ensure_user_data_dir(const char*id);
static int rebind_user_view(void){return system("/etc/init.d/S05nuubos-storage user-switch >/dev/null 2>&1");}
static int activate_user(const char*id){struct user_info u;char old[64],text[80];if(read_profile(id,&u))return-1;sync();active_id(old,sizeof(old));mkdir("/run/nuubos",0755);mkdir("/run/nuubos/user",0755);snprintf(text,sizeof(text),"%.36s\n",id);if(write_atomic_text(ACTIVE_FILE,text,0644))return-1;ensure_user_data_dir(id);if(rebind_user_view()!=0){if(old[0]){snprintf(text,sizeof(text),"%.36s\n",old);(void)write_atomic_text(ACTIVE_FILE,text,0644);}else unlink(ACTIVE_FILE);(void)rebind_user_view();return-1;}(void)update_config("LAST_USER",id);switch_requested=false;sync();return 0;}
static int remove_cb(const char*f,const struct stat*s,int t,struct FTW*b){(void)s;(void)t;(void)b;return remove(f);}static int rm_tree(const char*p){if(access(p,F_OK))return 0;return nftw(p,remove_cb,16,FTW_DEPTH|FTW_PHYS);}
static int ensure_user_data_dir(const char*id){char p[180];mkdir("/userdata/users",0755);snprintf(p,sizeof(p),"/userdata/users/%.36s",id);mkdir(p,0700);snprintf(p,sizeof(p),"/userdata/users/%.36s/profile",id);mkdir(p,0700);snprintf(p,sizeof(p),"/userdata/users/%.36s/profile/avatars",id);mkdir(p,0700);return 0;}
static int create_user(const char*name,char*out,size_t outsz){char id[64],dir[128],path[160],def[64];struct user_info u;FILE*f;if(!valid_name(name))return-1;f=fopen("/proc/sys/kernel/random/uuid","r");if(!f)return-1;if(!fgets(id,sizeof(id),f)){fclose(f);return-1;}fclose(f);trim(id);if(!valid_id(id))return-1;snprintf(dir,sizeof(dir),USERS_DIR"/%.36s",id);if(mkdir(dir,0700))return-1;snprintf(path,sizeof(path),"%s/secrets",dir);mkdir(path,0700);snprintf(path,sizeof(path),"%s/settings.conf",dir);if(write_atomic_text(path,"NUUBOS_USER_SETTINGS_VERSION=1\n",0600)){rm_tree(dir);return-1;}memset(&u,0,sizeof(u));snprintf(u.id,sizeof(u.id),"%.36s",id);snprintf(u.name,sizeof(u.name),"%.64s",name);snprintf(u.avatar,sizeof(u.avatar),"builtin:01");if(save_profile(&u)){rm_tree(dir);return-1;}ensure_user_data_dir(id);config_value("DEFAULT_USER",def,sizeof(def),"");if(!def[0])update_config("DEFAULT_USER",id);snprintf(out,outsz,"%.36s",id);sync();return 0;}
static int delete_user(const char*id){struct user_info users[MAX_USERS];int n,i;char active[64],def[64],last_user[64],path[180],replacement[64]="";if(!valid_id(id))return-1;active_id(active,sizeof(active));if(!strcmp(active,id))return-2;n=list_users(users,MAX_USERS);if(n<=1)return-3;for(i=0;i<n;i++)if(strcmp(users[i].id,id)){snprintf(replacement,sizeof(replacement),"%.36s",users[i].id);break;}snprintf(path,sizeof(path),USERS_DIR"/%.36s",id);if(rm_tree(path))return-1;snprintf(path,sizeof(path),"/userdata/users/%.36s",id);(void)rm_tree(path);config_value("DEFAULT_USER",def,sizeof(def),"");if(!strcmp(def,id)&&replacement[0])update_config("DEFAULT_USER",replacement);config_value("LAST_USER",last_user,sizeof(last_user),"");if(!strcmp(last_user,id)&&replacement[0])update_config("LAST_USER",replacement);sync();return 0;}
static int set_name(const char*id,const char*name){struct user_info u;if(!valid_name(name)||read_profile(id,&u))return-1;snprintf(u.name,sizeof(u.name),"%.64s",name);return save_profile(&u);}
static int set_avatar(const char*id,const char*spec){struct user_info u;char path[512];if(!safe_avatar_spec(spec)||read_profile(id,&u))return-1;snprintf(u.avatar,sizeof(u.avatar),"%.255s",spec);avatar_path(&u,path,sizeof(path));if(access(path,R_OK))return-1;return save_profile(&u);}
static void list_avatars(int fd,const char*id){int i;char line[1400],dir[180];for(i=1;i<=AVATAR_BUILTIN_COUNT;i++){snprintf(line,sizeof(line),"avatar=builtin:%02d\tAvatar %02d\t" AVATAR_DIR "/%02d.png\n",i,i,i);write_all(fd,line);}if(valid_id(id)){DIR*d;struct dirent*e;snprintf(dir,sizeof(dir),"/userdata/users/%.36s/profile/avatars",id);d=opendir(dir);if(d){while((e=readdir(d))){const char*dot;if(e->d_name[0]=='.'||strstr(e->d_name,"..")||strlen(e->d_name)>120)continue;dot=strrchr(e->d_name,'.');if(!dot || (strcasecmp(dot,".png") && strcasecmp(dot,".jpg") && strcasecmp(dot,".jpeg"))) continue;snprintf(line,sizeof(line),"avatar=custom:%s\t%s\t%s/%s\n",e->d_name,e->d_name,dir,e->d_name);write_all(fd,line);}closedir(d);}}write_all(fd,"end=1\n");}
static void handle_line(struct client*c,char*line){char*a,*b;trim(line);if(!strcmp(line,"STATUS")){send_status(c->fd);return;}if(!strcmp(line,"SUBSCRIBE")){c->subscribed=true;send_status(c->fd);return;}if(!strcmp(line,"REQUEST_SWITCH")){switch_requested=true;write_all(c->fd,"OK\n");notify_all();return;}if(!strcmp(line,"CANCEL_SWITCH")){switch_requested=false;write_all(c->fd,"OK\n");notify_all();return;}if(!strncmp(line,"LIST_AVATARS\t",13)){list_avatars(c->fd,line+13);return;}if(!strncmp(line,"ACTIVATE\t",9)){if(!activate_user(line+9)){write_all(c->fd,"OK\n");notify_all();}else write_all(c->fd,"ERR activate failed\n");return;}if(!strncmp(line,"CREATE\t",7)){char id[64];if(!create_user(line+7,id,sizeof(id))){char out[96];snprintf(out,sizeof(out),"OK %.36s\n",id);write_all(c->fd,out);notify_all();}else write_all(c->fd,"ERR create failed\n");return;}if(!strncmp(line,"SET_NAME\t",9)){a=line+9;b=strchr(a,'\t');if(!b){write_all(c->fd,"ERR args\n");return;}*b++='\0';if(!set_name(a,b)){write_all(c->fd,"OK\n");notify_all();}else write_all(c->fd,"ERR name failed\n");return;}if(!strncmp(line,"SET_AVATAR\t",11)){a=line+11;b=strchr(a,'\t');if(!b){write_all(c->fd,"ERR args\n");return;}*b++='\0';if(!set_avatar(a,b)){write_all(c->fd,"OK\n");notify_all();}else write_all(c->fd,"ERR avatar failed\n");return;}if(!strncmp(line,"DELETE\t",7)){a=line+7;b=strchr(a,'\t');if(!b||strcmp(b+1,"CONFIRM")){write_all(c->fd,"ERR confirmation required\n");return;}*b='\0';{int rc=delete_user(a);if(!rc){write_all(c->fd,"OK\n");notify_all();}else if(rc==-2)write_all(c->fd,"ERR active user\n");else if(rc==-3)write_all(c->fd,"ERR last user\n");else write_all(c->fd,"ERR delete failed\n");}return;}if(!strncmp(line,"SET_LOGIN_MODE\t",15)){a=line+15;if(strcmp(a,"select")&&strcmp(a,"default")){write_all(c->fd,"ERR mode\n");return;}if(!update_config("USER_LOGIN_MODE",!strcmp(a,"default")?"DEFAULT":"SELECT")){write_all(c->fd,"OK\n");notify_all();}else write_all(c->fd,"ERR persistence\n");return;}if(!strncmp(line,"SET_DEFAULT\t",12)){a=line+12;{struct user_info u;if(read_profile(a,&u)){write_all(c->fd,"ERR user\n");return;}}if(!update_config("DEFAULT_USER",a)){write_all(c->fd,"OK\n");notify_all();}else write_all(c->fd,"ERR persistence\n");return;}write_all(c->fd,"ERR unknown command\n");}
static void service_client(struct client*c){char tmp[512];ssize_t n=read(c->fd,tmp,sizeof(tmp)),i;if(n<=0){close(c->fd);c->fd=-1;c->subscribed=false;c->used=0;return;}for(i=0;i<n;i++){if(tmp[i]=='\n'){c->buf[c->used]='\0';handle_line(c,c->buf);c->used=0;}else if(c->used+1<sizeof(c->buf))c->buf[c->used++]=tmp[i];else c->used=0;}}
int main(void){int l,i;FILE*f;signal(SIGPIPE,SIG_IGN);signal(SIGTERM,on_signal);signal(SIGINT,on_signal);for(i=0;i<MAX_CLIENTS;i++)clients[i].fd=-1;mkdir(USERS_DIR,0700);migrate_profiles();{char active[64];active_id(active,sizeof(active));if(active[0])(void)update_config("LAST_USER",active);}l=make_listener();if(l<0)return 1;f=fopen(PIDFILE,"w");if(f){fprintf(f,"%ld\n",(long)getpid());fclose(f);}while(!stop_requested){struct pollfd fds[1+MAX_CLIENTS];int map[1+MAX_CLIENTS],n=0,j,rc;fds[n]=(struct pollfd){l,POLLIN,0};map[n++]=-1;for(i=0;i<MAX_CLIENTS;i++)if(clients[i].fd>=0){fds[n]=(struct pollfd){clients[i].fd,POLLIN|POLLHUP|POLLERR,0};map[n++]=i;}rc=poll(fds,(nfds_t)n,-1);if(rc<0){if(errno==EINTR)continue;break;}for(j=0;j<n;j++){if(!fds[j].revents)continue;if(map[j]<0){accept_clients(l);continue;}i=map[j];if(fds[j].revents&(POLLHUP|POLLERR)){close(clients[i].fd);clients[i].fd=-1;}else service_client(&clients[i]);}}for(i=0;i<MAX_CLIENTS;i++)if(clients[i].fd>=0)close(clients[i].fd);close(l);unlink(SOCKET_PATH);unlink(PIDFILE);return 0;}
