#include <ctype.h>
#include <errno.h>
#include <poll.h>
#include <signal.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/timerfd.h>
#include <sys/types.h>
#include <sys/un.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>
#define SOCKET "/run/nuubos/regionald.sock"
#define PIDFILE "/run/nuubos/regionald.pid"
#define CONFIG "/state/config/regional.conf"
#define LAST_SYNC "/state/time/last-sync"
#define ZONE_TAB "/usr/share/zoneinfo/zone1970.tab"
#define MAX_CLIENTS 8
#define RESYNC_SEC 21600
struct client{int fd;bool sub;char buf[512];size_t used;};struct state{char zone[128];bool auto_time;char keyboard[32];long last_sync;bool clock_valid;};static struct client cl[MAX_CLIENTS];static struct state st;static volatile sig_atomic_t stop;
static void sig(int x){(void)x;stop=1;}static int wa(int f,const char*s){size_t n=strlen(s);while(n){ssize_t w=write(f,s,n);if(w<0){if(errno==EINTR)continue;return-1;}s+=w;n-=(size_t)w;}return 0;}static void trim(char*s){size_t n=strlen(s);while(n&&isspace((unsigned char)s[n-1]))s[--n]='\0';char*p=s;while(*p&&isspace((unsigned char)*p))p++;if(p!=s)memmove(s,p,strlen(p)+1);}static bool token(const char*s){size_t i,n=strlen(s);if(!n||n>120||strstr(s,".."))return false;for(i=0;i<n;i++){unsigned char c=s[i];if(!(isalnum(c)||c=='/'||c=='_'||c=='-'||c=='+'))return false;}return true;}
static bool kv(const char*p,const char*k,char*out,size_t z){FILE*f=fopen(p,"r");char l[512];size_t n=strlen(k);if(!f)return false;while(fgets(l,sizeof(l),f)){trim(l);if(!strncmp(l,k,n)&&l[n]=='='){snprintf(out,z,"%s",l+n+1);fclose(f);return true;}}fclose(f);return false;}static long last(void){char v[64];return kv(LAST_SYNC,"LAST_NTP_SYNC",v,sizeof(v))?strtol(v,NULL,10):0;}static bool clock_ok(void){return time(NULL)>=1577836800;}
static void current_zone(char*out,size_t z){char l[256];ssize_t n=readlink("/etc/localtime",l,sizeof(l)-1);const char*p="/usr/share/zoneinfo/";if(n>0){l[n]='\0';if(!strncmp(l,p,strlen(p))&&token(l+strlen(p))){snprintf(out,z,"%.120s",l+strlen(p));return;}}snprintf(out,z,"UTC");}
static void load(void){char v[160];current_zone(st.zone,sizeof(st.zone));st.auto_time=true;snprintf(st.keyboard,sizeof(st.keyboard),"us");if(kv(CONFIG,"TIMEZONE",v,sizeof(v))&&token(v))snprintf(st.zone,sizeof(st.zone),"%.120s",v);if(kv(CONFIG,"AUTOMATIC_TIME",v,sizeof(v)))st.auto_time=strcmp(v,"0")!=0;if(kv(CONFIG,"KEYBOARD_LAYOUT",v,sizeof(v))&&token(v))snprintf(st.keyboard,sizeof(st.keyboard),"%.31s",v);st.last_sync=last();st.clock_valid=clock_ok();}
static int save(void){char t[384];FILE*f;mkdir("/state/config",0755);snprintf(t,sizeof(t),CONFIG".tmp.%ld",(long)getpid());f=fopen(t,"w");if(!f)return-1;fprintf(f,"REGIONAL_CONFIG_VERSION=1\nTIMEZONE=%s\nAUTOMATIC_TIME=%d\nKEYBOARD_LAYOUT=%s\n",st.zone,st.auto_time?1:0,st.keyboard);if(fflush(f)||fsync(fileno(f))){fclose(f);unlink(t);return-1;}fclose(f);chmod(t,0600);if(rename(t,CONFIG)){unlink(t);return-1;}return 0;}static int run(char*const a[]){pid_t p=fork();int x;if(p<0)return-1;if(!p){execv(a[0],a);_exit(127);}while(waitpid(p,&x,0)<0&&errno==EINTR){}return WIFEXITED(x)?WEXITSTATUS(x):-1;}
static int apply_zone(const char*z){char src[256],tmp[128],tz_tmp[128];FILE*f;if(!token(z))return-1;snprintf(src,sizeof(src),"/usr/share/zoneinfo/%.120s",z);if(access(src,R_OK))return-1;snprintf(tmp,sizeof(tmp),"/etc/.localtime.%ld",(long)getpid());unlink(tmp);if(symlink(src,tmp)||rename(tmp,"/etc/localtime")){unlink(tmp);return-1;}snprintf(tz_tmp,sizeof(tz_tmp),"/etc/.timezone.%ld",(long)getpid());f=fopen(tz_tmp,"w");if(!f)return-1;if(fprintf(f,"%s\n",z)<0||fflush(f)||fsync(fileno(f))){fclose(f);unlink(tz_tmp);return-1;}fclose(f);if(rename(tz_tmp,"/etc/timezone")){unlink(tz_tmp);return-1;}return 0;}static int apply_keyboard(const char*k){char*a1[]={(char*)"/usr/bin/loadkeys",(char*)"-q",(char*)k,NULL};char*a2[]={(char*)"/bin/loadkeys",(char*)"-q",(char*)k,NULL};if(!token(k))return-1;if(!access(a1[0],X_OK))return run(a1);if(!access(a2[0],X_OK))return run(a2);return-1;}static int sync_now(void){char*a[]={(char*)"/usr/sbin/nuubos-timectl",(char*)"sync",NULL};int rc=run(a);load();return rc;}
static int adjust_local_clock(long delta){struct timespec ts;if(clock_gettime(CLOCK_REALTIME,&ts))return-1;ts.tv_sec+=(time_t)delta;if(clock_settime(CLOCK_REALTIME,&ts))return-1;st.clock_valid=clock_ok();return 0;}static void local_labels(char*d,size_t dz,char*t,size_t tz){time_t now=time(NULL);struct tm tmv;if(localtime_r(&now,&tmv)==NULL){snprintf(d,dz,"---- -- --");snprintf(t,tz,"--:--");return;}strftime(d,dz,"%Y-%m-%d",&tmv);strftime(t,tz,"%H:%M",&tmv);}static void status(int f){char b[640],d[32],t[32];local_labels(d,sizeof(d),t,sizeof(t));snprintf(b,sizeof(b),"timezone=%s\nautomatic_time=%d\nkeyboard_layout=%s\nlast_sync=%ld\nclock_valid=%d\nlocal_date=%s\nlocal_time=%s\n",st.zone,st.auto_time?1:0,st.keyboard,st.last_sync,st.clock_valid?1:0,d,t);wa(f,b);}static void notify(void){int i;for(i=0;i<MAX_CLIENTS;i++)if(cl[i].fd>=0&&cl[i].sub)status(cl[i].fd);}static void zones(int f){FILE*x=fopen(ZONE_TAB,"r");char l[512];wa(f,"zone=UTC\n");if(x){while(fgets(l,sizeof(l),x)){char*a,*z;trim(l);if(!l[0]||l[0]=='#')continue;a=strchr(l,'\t');if(!a)continue;a=strchr(a+1,'\t');if(!a)continue;z=a+1;a=strchr(z,'\t');if(a)*a='\0';trim(z);if(token(z)){char o[220];snprintf(o,sizeof(o),"zone=%.120s\n",z);wa(f,o);}}fclose(x);}wa(f,"end=1\n");}static void keyboards(int f){static const char*rows[]={"us\tEnglish (US)\tqwerty","uk\tEnglish (UK)\tqwerty","it\tItaliano\tqwerty","fr\tFrançais\tazerty","de\tDeutsch\tqwertz","es\tEspañol\tqwerty","pt-latin1\tPortuguês\tqwerty"};size_t i;char b[160];for(i=0;i<sizeof(rows)/sizeof(rows[0]);i++){snprintf(b,sizeof(b),"keyboard=%s\n",rows[i]);wa(f,b);}wa(f,"end=1\n");}
static int listener(void){int f;struct sockaddr_un a;mkdir("/run/nuubos",0755);unlink(SOCKET);f=socket(AF_UNIX,SOCK_STREAM|SOCK_NONBLOCK|SOCK_CLOEXEC,0);if(f<0)return-1;memset(&a,0,sizeof(a));a.sun_family=AF_UNIX;snprintf(a.sun_path,sizeof(a.sun_path),"%s",SOCKET);if(bind(f,(struct sockaddr*)&a,sizeof(a))||listen(f,8)){close(f);return-1;}chmod(SOCKET,0660);return f;}static int timer(void){int f=timerfd_create(CLOCK_BOOTTIME,TFD_NONBLOCK|TFD_CLOEXEC);struct itimerspec it={0};if(f<0)return-1;it.it_value.tv_sec=RESYNC_SEC;it.it_interval.tv_sec=RESYNC_SEC;if(timerfd_settime(f,0,&it,NULL)){close(f);return-1;}return f;}static void accept_clients(int l){for(;;){int f=accept4(l,NULL,NULL,SOCK_NONBLOCK|SOCK_CLOEXEC),i;if(f<0)return;for(i=0;i<MAX_CLIENTS;i++)if(cl[i].fd<0)break;if(i==MAX_CLIENTS){close(f);continue;}cl[i]=(struct client){.fd=f};}}
static void command(struct client*c,char*l){char*v;trim(l);if(!strcmp(l,"STATUS")){status(c->fd);return;}if(!strcmp(l,"SUBSCRIBE")){c->sub=true;status(c->fd);return;}if(!strcmp(l,"LIST_TIMEZONES")){zones(c->fd);return;}if(!strcmp(l,"LIST_KEYBOARDS")){keyboards(c->fd);return;}if(!strcmp(l,"SYNC_NOW")){if(!sync_now()){wa(c->fd,"OK\n");notify();}else wa(c->fd,"ERR sync failed\n");return;}if(!strncmp(l,"SET_TIMEZONE\t",13)){v=l+13;if(!apply_zone(v)){snprintf(st.zone,sizeof(st.zone),"%.120s",v);if(!save()){wa(c->fd,"OK\n");notify();return;}}wa(c->fd,"ERR timezone\n");return;}if(!strncmp(l,"SET_AUTOMATIC_TIME\t",19)){v=l+19;if(strcmp(v,"0")&&strcmp(v,"1")){wa(c->fd,"ERR value\n");return;}st.auto_time=!strcmp(v,"1");if(!save()){wa(c->fd,"OK\n");notify();if(st.auto_time)(void)sync_now();}else wa(c->fd,"ERR persistence\n");return;}if(!strncmp(l,"ADJUST_LOCAL_MINUTES\t",21)){long n=strtol(l+21,NULL,10);if(st.auto_time){wa(c->fd,"ERR automatic time enabled\n");return;}if(n<-1440||n>1440||adjust_local_clock(n*60L)){wa(c->fd,"ERR time\n");return;}wa(c->fd,"OK\n");notify();return;}if(!strncmp(l,"ADJUST_LOCAL_DAYS\t",18)){long n=strtol(l+18,NULL,10);if(st.auto_time){wa(c->fd,"ERR automatic time enabled\n");return;}if(n<-366||n>366||adjust_local_clock(n*86400L)){wa(c->fd,"ERR date\n");return;}wa(c->fd,"OK\n");notify();return;}if(!strncmp(l,"SET_KEYBOARD\t",13)){v=l+13;if(!apply_keyboard(v)){snprintf(st.keyboard,sizeof(st.keyboard),"%.31s",v);if(!save()){wa(c->fd,"OK\n");notify();return;}}wa(c->fd,"ERR keyboard\n");return;}wa(c->fd,"ERR unknown command\n");}
static void service(struct client*c){char b[256];ssize_t n=read(c->fd,b,sizeof(b)),i;if(n<=0){close(c->fd);c->fd=-1;c->sub=false;c->used=0;return;}for(i=0;i<n;i++){if(b[i]=='\n'){c->buf[c->used]='\0';command(c,c->buf);c->used=0;}else if(c->used+1<sizeof(c->buf))c->buf[c->used++]=b[i];else c->used=0;}}
int main(void){int l,t,i;FILE*f;signal(SIGPIPE,SIG_IGN);signal(SIGTERM,sig);signal(SIGINT,sig);for(i=0;i<MAX_CLIENTS;i++)cl[i].fd=-1;load();(void)apply_zone(st.zone);(void)apply_keyboard(st.keyboard);l=listener();t=timer();if(l<0)return 1;f=fopen(PIDFILE,"w");if(f){fprintf(f,"%ld\n",(long)getpid());fclose(f);}while(!stop){struct pollfd p[2+MAX_CLIENTS];int map[2+MAX_CLIENTS],n=0,j,rc;p[n]=(struct pollfd){l,POLLIN,0};map[n++]=-1;if(t>=0){p[n]=(struct pollfd){t,POLLIN,0};map[n++]=-2;}for(i=0;i<MAX_CLIENTS;i++)if(cl[i].fd>=0){p[n]=(struct pollfd){cl[i].fd,POLLIN|POLLHUP|POLLERR,0};map[n++]=i;}rc=poll(p,(nfds_t)n,-1);if(rc<0){if(errno==EINTR)continue;break;}for(j=0;j<n;j++){if(!p[j].revents)continue;if(map[j]==-1){accept_clients(l);continue;}if(map[j]==-2){uint64_t e;while(read(t,&e,sizeof(e))>0){}if(st.auto_time){(void)sync_now();notify();}continue;}i=map[j];if(p[j].revents&(POLLHUP|POLLERR)){close(cl[i].fd);cl[i].fd=-1;}else service(&cl[i]);}}for(i=0;i<MAX_CLIENTS;i++)if(cl[i].fd>=0)close(cl[i].fd);if(t>=0)close(t);close(l);unlink(SOCKET);unlink(PIDFILE);return 0;}
