[package]
name = "nuubos-quick-menu"
version = "0.1.0"
edition = "2021"
build = "build.rs"
license = "MIT"

[dependencies]
slint = { version = "=1.18.1", default-features = false, features = ["std", "backend-winit", "renderer-software", "compat-1-18"] }
wayland-client = "=0.31.15"
wayland-protocols-wlr = { version = "=0.3.12", features = ["client"] }

[build-dependencies]
slint-build = "=1.18.1"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
strip = true
